spring.application.name=flexapp

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
jwt.secret=${JWT_SECRET}
cors.allowed-origins=${CORS_ORIGIN}
security.trusted-proxies=${TRUSTED_PROXIES:127.0.0.1/32,::1/128}

spring.jpa.hibernate.ddl-auto=update

cookie.secure=true