spring.application.name=flexapp

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
jwt.secret=${JWT_SECRET}
cors.allowed-origins=${CORS_ORIGIN}

spring.profiles.active=dev
spring.jpa.hibernate.ddl-auto=update

cookie.secure=true